version: "3.5"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_DB: my_db
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: always
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always